labels:
  backend: local

steps:
  check:
    when:
      - event: pull_request
        repo: test/test
      - event: push
        branch: trunk
    image: bash
    commands:
      -  nix flake check --all-systems # TODO: more systems maybe? (also nix-on-droid check)
