#!/bin/sh
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

if [ "$EUID" -eq 0 ]; then
    SUDO=""
else
    SUDO="sudo"
fi

echo -e "${BLUE}copying configuration files to /etc/nixos/${NC}"
echo -e "${BLUE}backing up configuration files to backnix/${NC}"
$SUDO cp -r /etc/nixos/* backnix/
echo -e "${RED}CLEANING OLD CONFIG${NC}"
# yes, its wheelchair
$SUDO find /etc/nixos -mindepth 1 -maxdepth 1 ! -name 'hardware-configuration.nix' -exec rm -rf {} +
echo -e "${BLUE}copying new configuration files to /etc/nixos/${NC}"
$SUDO mkdir -p /etc/nixos/ssh
$SUDO mkdir -p /etc/nixos/packages
$SUDO mkdir -p /etc/nixos/critical
$SUDO mkdir -p /etc/nixos/mics
$SUDO mkdir -p /etc/nixos/services
$SUDO mkdir -p /etc/nixos/security
$SUDO cp -r ./ssh/* /etc/nixos/ssh/
$SUDO cp -r ./packages/* /etc/nixos/packages/
$SUDO cp -r ./critical/* /etc/nixos/critical/
$SUDO cp -r ./mics/* /etc/nixos/mics/
$SUDO cp -r ./services/* /etc/nixos/services/
$SUDO cp -r ./security/* /etc/nixos/security/
$SUDO cp ./configuration.nix /etc/nixos/configuration.nix
echo -e "${GREEN}DONE${NC}"
echo -e "${CYAN}rebuilding${NC}"
$SUDO nixos-rebuild switch