{
  config,
  lib,
  pkgs,
  ...
}:

{
  imports = [
    ./hardware-configuration.nix # some autogenerated shit
    ./ssh/ssh.nix
    ./packages
    ./critical
    ./http
  ];

  time.timeZone = "Europe/Moscow";
  system.stateVersion = "25.11";
}
